### ISSUE TITLE
dbnsetup.m early_stopping check might be invalid

### ISSUE THREAD

**Issue by kkm000** [skaae/rbm_toolbox#1]
First of all, `test_example_DBN.m` does not work (ML 2014):

```
>> test_example_DBN
Error using dbnsetup (line 39)
Early stopping is not implemented for generativeRBM
```

The check at line 39 does not look right to me. Did you mean instead

```
if opts.early_stopping
    if opts.classRBM == 1
        if  reqboth('y_val','x_val')
            error('Eearly stopping with classRBM requires x and y val sets')
        end
    else
        error('Early stopping is not implemented for generativeRBM')
    end
end
```

**Comment by skaae** [comment]
It's work in progress. I think only example 1 and 2 are working at the moment. I'm working on the docs and test/examples at the moment. 

I think you are correct i'll change the check to:

```
if opts.early_stopping
    if opts.classRBM == 1
        if  reqboth('y_val','x_val')
            error('Eearly stopping with classRBM requires x and y val sets')
        end
    elseif opts.classRBM == 0
         error('Early stopping is not implemented for generativeRBM')
    end   
end
```

**Comment by kkm000** [comment]
Thanks for fixing these quickly. Are there other values for opts.classRBM than 1 and 0? I thought it was treated as a boolean.

Not sure what is the best way to contact you, but I wanted to tell that I am using your code in a real learning application (speech recognition related), and want to improve the NN part of it. The reason is backprop is still superior a fine-tuning method, albeit much slower than CD for RBM. I am going to unify the GPU code for NN so that there are no 2×3 separate files to maintain (GPU gives me a 8x boost in speed, overnight vs a week!), and also add a couple of other features lacking.

So this is in essence a collaboration proposal. How do you think we should better handle that, assuming you are interested at all: Should I fork and propose pulls, or do you think we can work in the same repo? I could do a branch and let you review the code and settle down all question before merging--no merge until you'd give an LGTM. The new features I'd discuss with you upfront, so we can attach the code on both DBN and NN fronts. This code certainly has too many forks already! : ) What do you think?

EDIT: my email is kkm at pobox period com.
